config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :tweets

  # devise_for :users, path_names: { sign_in: 'signin', sign_out: 'signout' },
  #                  controllers: { omniauth_callbacks: 'omniauth_callbacks',
  #                                 registrations: 'registrations' }
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations"}

  resources :users
  resources :entries
  resources :displays
  resources :authentications, only: [:destroy]

  root 'page#dashboard'
  get  '/preview' => 'page#previewmode'
  get '/test' => 'page#test'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :display
  has_many :tweets, dependent: :destroy

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
    @displays = Display.all
  end

  # GET /entries/1/edit
  def edit
    @displays = Display.all
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        search_images_by_hashtag(@entry.id)
        format.html { redirect_to root_path, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to root_path, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:entry_name, :display_id, :hashtag, :account_name, :fill_percentage, :account_active, :hashtag_active)
    end

    def current_user_token
      current_user.twitter_authentication.token
    end

    def current_user_secret
      current_user.twitter_authentication.secret
    end

    def search_images_by_hashtag(entry)
      @entries = Entry.all
      @hashtags = @entries.map(&:hashtag)
      hashtag = @hashtags.last

      pound_and_tag = "#" + hashtag
      #Use SideKiq worker to perform tweet search for tweets that use hashtag
      HashtagSearchWorker.perform_async(pound_and_tag, current_user_token, current_user_secret, entry)
    end

    def search_images_by_account

    end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_name %>
    <%= f.text_field :entry_name %>
  </div>

  <div class="form-group">
      <%= f.collection_select :display_id, @displays, :id, :name, {:include_blank => 'Select a Display'}, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :hashtag %>
    <%= f.text_field :hashtag %>
  </div>

  <div class="field">
    <%= f.label :account_name %>
    <%= f.text_field :account_name %>
  </div>

  <div class="field">
    <%= f.label :fill_percentage %>
    <%= f.number_field :fill_percentage %>
  </div>

  <div class="field">
    <%= f.label :account_active %>
    <%= f.check_box :account_active %>
  </div>

  <div class="field">
    <%= f.label :hashtag_active %>
    <%= f.check_box :hashtag_active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Entry name</th>
      <th>Display</th>
      <th>Hashtag</th>
      <th>Account name</th>
      <th>Fill percentage</th>
      <th>Account active</th>
      <th>Hashtag active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.entry_name %></td>
        <td><%= entry.display_id %></td>
        <td><%= entry.hashtag %></td>
        <td><%= entry.account_name %></td>
        <td><%= entry.fill_percentage %></td>
        <td><%= entry.account_active %></td>
        <td><%= entry.hashtag_active %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry name:</strong>
  <%= @entry.entry_name %>
</p>

<p>
  <strong>Display:</strong>
  <%= @entry.display_id %>
</p>

<p>
  <strong>Hashtag:</strong>
  <%= @entry.hashtag %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @entry.account_name %>
</p>

<p>
  <strong>Fill percentage:</strong>
  <%= @entry.fill_percentage %>
</p>

<p>
  <strong>Account active:</strong>
  <%= @entry.account_active %>
</p>

<p>
  <strong>Hashtag active:</strong>
  <%= @entry.hashtag_active %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>