config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :tweets

  # devise_for :users, path_names: { sign_in: 'signin', sign_out: 'signout' },
  #                  controllers: { omniauth_callbacks: 'omniauth_callbacks',
  #                                 registrations: 'registrations' }
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations"}

  resources :users
  resources :entries
  resources :displays
  resources :authentications, only: [:destroy]

  root 'page#dashboard'
  get  '/preview' => 'page#previewmode'
  get '/test' => 'page#test'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/display.rb
# Schema for Display Table 
# create_table "displays", force: :cascade do |t|
#   t.string   "name"
#   t.boolean  "active_content"
#   t.datetime "created_at",     null: false
#   t.datetime "updated_at",     null: false
#   t.string   "file"
#   t.integer  "user_id"
#   t.index ["user_id"], name: "index_displays_on_user_id", using: :btree
# end

class Display < ApplicationRecord
  belongs_to :user
  has_many :entries, dependent: :destroy

  validates :file, presence: true
  validates :name, presence: true

  default_scope { order('created_at DESC')}
  scope :active_content, ->{ where(:active_content => true).order("created_at DESC") }

  mount_uploader :file, FileUploader






end

app/controllers/displays_controller.rb
class DisplaysController < ApplicationController
  before_action :set_display, only: [:show, :edit, :update, :destroy]

  # GET /displays
  # GET /displays.json
  def index
    @displays = Display.all
  end

  # GET /displays/1
  # GET /displays/1.json
  def show
  end

  # GET /displays/new
  def new
    @display = Display.new
  end

  # GET /displays/1/edit
  def edit
  end

  # POST /displays
  # POST /displays.json
  def create
    @display = Display.new(display_params)
    @display.user = current_user

    respond_to do |format|
      if @display.save
        format.html { redirect_to root_path, notice: 'Display was successfully created.' }
        format.json { render :show, status: :created, location: @display }
      else
        format.html { render :new }
        format.json { render json: @display.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /displays/1
  # PATCH/PUT /displays/1.json
  def update
    respond_to do |format|
      if @display.update(display_params)
        format.html { redirect_to @display, notice: 'Display was successfully updated.' }
        format.json { render :show, status: :ok, location: @display }
      else
        format.html { render :edit }
        format.json { render json: @display.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /displays/1
  # DELETE /displays/1.json
  def destroy
    @display.destroy
    respond_to do |format|
      format.html { redirect_to displays_url, notice: 'Display was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_display
      @display = Display.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def display_params
      params.require(:display).permit(:name, :active_content, :file, :user_id)
    end
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/views/displays/_form.html.erb
<%= form_for(display) do |f| %>
  <% if display.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(display.errors.count, "error") %> prohibited this display from being saved:</h2>

      <ul>
      <% display.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :active_content %>
    <%= f.check_box :active_content %>
  </div>

  <div class="form-control">
    <%= f.file_field :file, multiple: false, accept: ".jpg, .jpeg, .gif, .png, .mp4, .m4v, .webm, .ogg, .pdf", required: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/displays/edit.html.erb
<h1>Editing Display</h1>

<%= render 'form', display: @display %>

<%= link_to 'Show', @display %> |
<%= link_to 'Back', displays_path %>

app/views/displays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Displays</h1>

<table>
  <thead>
    <tr>
      <th>Display name</th>
      <th>Active Content</th>
      <th>
        Display
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @displays.each do |display| %>
      <tr>
        <td><%= display.name %></td>
        <td><%= display.active_content %></td>
        <td><%= image_tag display.file %></td>
        <td><%= link_to 'Show', display %></td>
        <td><%= link_to 'Edit', edit_display_path(display) %></td>
        <td><%= link_to 'Destroy', display, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Display', new_display_path %>

app/views/displays/new.html.erb
<h1>New Display</h1>

<%= render 'form', display: @display %>

<%= link_to 'Back', displays_path %>

app/views/displays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry name:</strong>
  <%= @display.name %>
</p>

<p>
  <strong>Display:</strong>
  <%= @display.active_content %>
</p>

<p>


<%= link_to 'Edit', edit_display_path(@display) %> |
<%= link_to 'Back', displays_path %>