config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :tweets

  # devise_for :users, path_names: { sign_in: 'signin', sign_out: 'signout' },
  #                  controllers: { omniauth_callbacks: 'omniauth_callbacks',
  #                                 registrations: 'registrations' }
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations"}

  resources :users
  resources :entries
  resources :displays
  resources :authentications, only: [:destroy]

  root 'page#dashboard'
  get  '/preview' => 'page#previewmode'
  get '/test' => 'page#test'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dot Powered by Conexus", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">

      <% if current_user.instagram_authenticated? %>
      <div class="nav navbar-nav navbar-left">
        <p class="navbar-text" id="status-display"><%= link_to "View in Preview Mode", preview_path %></p>
      </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <% if current_user.instagram_authenticated? %>
          <!-- <li class="instagram-icon">
            <%= image_tag "instagram_icon.png", height: 25, width: 25 %>
          </li> -->

          <% else %>
          <li>
            <%= link_to user_instagram_omniauth_authorize_path(scope: "basic public_content relationships likes") do %>
              <%= image_tag "instagram_icon.png", height: 25, width: 25, class: "inactive", data: { toggle: 'tooltip', placement: 'bottom' }, title: "Authorize Instagram" %>
            <% end %>
          </li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-cog"></span>
          </a>
          <ul class="dropdown-menu">
              <li><%= link_to "Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Create account", new_user_registration_path %></li>
        <li><%= link_to "Sign in", login_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dotapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= html_import_tag 'application'%>
  </head>

  <body>
    <% if current_user %>
    <%= render 'layouts/navbar' %>
    <% end %>


    <%= yield %>

  </body>
</html>